name: Deploy spring boot - react app
on: 
    push:
        branches:
            - main
jobs:
    test_spring_boot:
        runs-on: ubuntu-latest
        container:
            image: eclipse-temurin:25
        steps:
            - name: download spring boot code
              uses: actions/checkout@v6
            # - name: setup java
            #   uses: actions/setup-java@v5
            #   with:
            #     distribution: 'temurin'
            #     java-version: '25'
            #     cache: maven
            - name: Compile code
              run: |
                 chmod +x mvnw
                 ./mvnw -B clean compile
              working-directory: backend

            - name: test code
              run: |
                 chmod +x mvnw
                 ./mvnw -B clean verify
              working-directory: backend

            - name: Upload compiled classes
              uses: actions/upload-artifact@v4
              with:
                  name: compiled-classes
                  path: backend/target/classes
    test_react:
        needs: test_spring_boot
        runs-on: ubuntu-latest
        container:
            image: node:22
        steps:
            - name: download spring boot code
              uses: actions/checkout@v6
            # - name: setup node
            #   uses: actions/setup-node@v3
            #   with:
            #     node-version: 22
            - name: Cache NPM dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.OS }}-npm-cache-
            - name: npm dependencies
              run: npm ci
              working-directory: frontend
            - name: test react
              run: npm run lint
              working-directory: frontend
            - name: build react
              run: npm run build
              working-directory: frontend
            - name: upload dist folder
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: frontend/dist